# Generated by Django 3.0.3 on 2020-02-08 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заглавие')),
                ('mini_text', models.TextField(verbose_name='Описание')),
                ('text', models.TextField(verbose_name='Текст')),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
